---
name: github
provider: github.com
repository: docker-svgtools
url: https://github.com/cardboardci/docker-svgtools
clone:
  ssh: git@github.com:cardboardci/docker-svgtools.git
  https: https://github.com/cardboardci/docker-svgtools.git